### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by mckennajones** [JakeJeffreys/aggregator-spring#1]
Can you please update the Readme with instructions on how to build and run this? I'd like to use it for an upcoming project of mine. Thanks!

**Comment by mckennajones** [comment]
@JakeJeffreys any update here?

**Comment by jjeffreys** [comment]
Thanks for the suggestion friend! I'll take that into account and get back to you shortly.

**Comment by JakeJeffreys** [comment]
Deprioritized.
